# Generated by Django 3.1.4 on 2021-02-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('course', models.CharField(max_length=140)),
                ('rating', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cele', models.CharField(max_length=200)),
                ('rozwiniecie', models.CharField(max_length=200)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.dni')),
            ],
            options={
                'ordering': ['cele'],
            },
        ),
    ]
