# Generated by Django 3.1.4 on 2021-02-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_auto_20210220_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dni',
            name='rating',
        ),
    ]
