# Generated by Django 3.1.4 on 2021-02-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0004_remove_dni_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dni',
            options={'ordering': ['nazwa']},
        ),
        migrations.RenameField(
            model_name='dni',
            old_name='name',
            new_name='nazwa',
        ),
    ]
