# Generated by Django 3.1.4 on 2021-02-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0005_auto_20210220_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cele',
            old_name='rozwiniecie',
            new_name='check',
        ),
    ]
