# Generated by Django 3.1.4 on 2021-02-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0006_auto_20210220_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dni',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='dni',
            old_name='nazwa',
            new_name='title',
        ),
    ]
