# Generated by Django 3.1.4 on 2021-02-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0007_auto_20210225_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dni',
            old_name='co',
            new_name='detail',
        ),
    ]
